/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'test' at '17-3-21 下午6:19' with Gradle 2.2.1
 *
 * @author test, @date 17-3-21 下午6:19
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
